In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mlb
import numpy as np
import math as m

In [2]:
df = pd.read_csv('transfusion.data')                         #loading the dataset

In [3]:
df.head()

Recency (months)  Frequency (times)  Monetary (c.c. blood)  Time (months)  \
0                 2                 50                  12500             98   
1                 0                 13                   3250             28   
2                 1                 16                   4000             35   
3                 2                 20                   5000             45   
4                 1                 24                   6000             77   

   whether he/she donated blood in March 2007  
0                                           1  
1                                           1  
2                                           1  
3                                           1  
4                                           0

In [4]:
df.rename(columns={'whether he/she donated blood in March 2007':'class'},inplace = True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Recency (months)       748 non-null    int64
 1   Frequency (times)      748 non-null    int64
 2   Monetary (c.c. blood)  748 non-null    int64
 3   Time (months)          748 non-null    int64
 4   class                  748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB


In [6]:
df.isnull().any()

Recency (months)         False
Frequency (times)        False
Monetary (c.c. blood)    False
Time (months)            False
class                    False
dtype: bool

In [7]:
df.describe()

Recency (months)  Frequency (times)  Monetary (c.c. blood)  \
count        748.000000         748.000000             748.000000   
mean           9.506684           5.514706            1378.676471   
std            8.095396           5.839307            1459.826781   
min            0.000000           1.000000             250.000000   
25%            2.750000           2.000000             500.000000   
50%            7.000000           4.000000            1000.000000   
75%           14.000000           7.000000            1750.000000   
max           74.000000          50.000000           12500.000000   

       Time (months)       class  
count     748.000000  748.000000  
mean       34.282086    0.237968  
std        24.376714    0.426124  
min         2.000000    0.000000  
25%        16.000000    0.000000  
50%        28.000000    0.000000  
75%        50.000000    0.000000  
max        98.000000    1.000000

In [8]:
target_incidence = df['class'].value_counts()

In [9]:
target_incidence               # count of o's and 1's

0    570
1    178
Name: class, dtype: int64

In [10]:
(570/(570+178))*100            # percentage of people not donoting

76.20320855614973

In [11]:
target = df['class'].values

In [12]:
target

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [13]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [14]:
from sklearn.model_selection import train_test_split                       #splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, stratify = df['class'])

In [15]:
X_train

array([[    5,    46, 11500,    98],
       [   39,     1,   250,    39],
       [    9,     9,  2250,    45],
       ...,
       [    0,    26,  6500,    76],
       [   14,     3,   750,    28],
       [   23,     2,   500,    23]], dtype=int64)

In [16]:
X_test

array([[   23,     1,   250,    23],
       [    2,     2,   500,     2],
       [   14,     3,   750,    26],
       [   11,     4,  1000,    27],
       [    4,     2,   500,    14],
       [    4,     5,  1250,    11],
       [    5,     6,  1500,    28],
       [    7,    10,  2500,    47],
       [    2,     2,   500,    41],
       [    4,     9,  2250,    55],
       [    4,     6,  1500,    41],
       [   23,     1,   250,    23],
       [    4,     6,  1500,    38],
       [    9,     3,   750,    14],
       [   11,     4,  1000,    74],
       [   11,    10,  2500,    35],
       [   11,     6,  1500,    26],
       [    9,     5,  1250,    19],
       [    2,     4,  1000,    16],
       [   23,     3,   750,    62],
       [    2,     6,  1500,    22],
       [    4,     2,   500,    51],
       [   23,     1,   250,    23],
       [   11,     7,  1750,    37],
       [   12,    12,  3000,    58],
       [   21,     1,   250,    21],
       [    2,    14,  3500,    48],
 

In [17]:
y_train

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,

In [18]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

In [1]:
pip install tpot                            #installing TPOT

  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11959 sha256=c02518c2cb588d204c1faa0d77b6c5da77e5892439dcefd42f9eb514ac6b6502
  Stored in directory: c:\users\anushar\appdata\local\pip\cache\wheels\e2\d2\79\eaf81edb391e27c87f51b8ef901ecc85a5363dc96b8b8d71e3
Successfully built stopit
Note: you may need to restart the kernel to use updated packages.


In [19]:
from tpot import TPOTClassifier

C:\Users\AnushaR\anaconda3\lib\site-packages\tpot\builtins\__init__.py:36: UserWarning: Warning: optional dependency `torch` is not available. - skipping import of NN models.
  warnings.warn("Warning: optional dependency `torch` is not available. - skipping import of NN models.")


In [20]:
tpot = TPOTClassifier(generations=5, verbosity=2)

In [21]:
tpot.fit(X_train,y_train)

Exception ignored in: <function Booster.__del__ at 0x0000013503E5DF78>
Traceback (most recent call last):
  File "C:\Users\AnushaR\anaconda3\lib\site-packages\xgboost\core.py", line 975, in __del__
    _check_call(_LIB.XGBoosterFree(self.handle))
stopit.utils.TimeoutException



Generation 1 - Current best internal CV score: 0.7860777496839444
Generation 2 - Current best internal CV score: 0.7949747155499368
Generation 3 - Current best internal CV score: 0.7949747155499368
Generation 4 - Current best internal CV score: 0.7949747155499368
Generation 5 - Current best internal CV score: 0.7950063211125158
Best pipeline: RandomForestClassifier(input_matrix, bootstrap=False, criterion=gini, max_features=0.15000000000000002, min_samples_leaf=13, min_samples_split=13, n_estimators=100)


TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=5,
               log_file=<ipykernel.iostream.OutStream object at 0x000001357D5E5488>,
               max_eval_time_mins=5, max_time_mins=None, memory=None,
               mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=100,
               random_state=None, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)

In [22]:
print(tpot.score(X_test,y_test))

0.8021390374331551


In [25]:
from sklearn.preprocessing import MinMaxScaler            #Log normalization
scaler = MinMaxScaler()

In [26]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, bootstrap=False, max_features=0.15000000000000002, criterion = 'gini', min_samples_leaf=13, min_samples_split=13)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None,
                       max_features=0.15000000000000002, max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=13,
                       min_samples_split=13, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [30]:
y_pred = classifier.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm = confusion_matrix(y_pred, y_test)

In [39]:
cm

array([[135,  27],
       [  8,  17]], dtype=int64)

In [40]:
accuracy_score(y_test, y_pred)

0.8128342245989305

In [41]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.83      0.94      0.89       143\n           1       0.68      0.39      0.49        44\n\n    accuracy                           0.81       187\n   macro avg       0.76      0.67      0.69       187\nweighted avg       0.80      0.81      0.79       187\n'

## As one prominent example, blood donations slow down during busy holiday seasons.